//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDatatransactionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int tra_id { get; set; }
        public string tra_accountnumber { get; set; }
        public string tra_beneficiaryname { get; set; }
        public string tra_bankname { get; set; }
        public string tra_SWIFTCode { get; set; }
        public Nullable<int> tra_amount { get; set; }
        public Nullable<System.DateTime> tra_datetime { get; set; }
    }
}
